### PR TITLE
Update logo to full SVG

### PR DESCRIPTION
**Pull request by tayloramurphy**
Updates the logo to use the SVG Florian made!

Closes https://github.com/meltano/hub/issues/921

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@cjohnhanson I may need an assist on this. The logo looks good but it probably needs to be bumped up in size just a tad.

**Comment by WillDaSilva** [comment]
> I may need an assist on this. The logo looks good but it probably needs to be bumped up in size just a tad.

@tayloramurphy Done in b94712759f957bf0e07134bc889396d444588600

**Comment by WillDaSilva** [comment]
@tayloramurphy This PR seems to fix #921. I have updated the PR description to close the issue when this PR is merged.

**Review by WillDaSilva — APPROVED** [review]

**Comment by tayloramurphy** [comment]
LGTM! Thank you @WillDaSilva :)

**Pull request merged**
