### PR TITLE
[fix] Add Missing Env Var to BQ

### PR DESCRIPTION
**Pull request by z3z1ma**
Adds `env` to config for `GOOGLE_APPLICATION_CREDENTIALS` which the tap required.

### CODE REVIEW

**Review by pnadolny13 — CHANGES_REQUESTED** [review]
@z3z1ma thanks for the PR! I left a similar comment [on your other PR](https://github.com/meltano/hub/pull/595#pullrequestreview-1004327641), would you mind doing the same here and not updating any formatting for the PR so its easier to see whats actually changing vs just being reformatted?

**Comment by z3z1ma** [comment]
Good to go, probably just squash commit

**Comment by z3z1ma** [comment]
@pnadolny13 
Correct, neither target will work out of the box without that. `env_alias` which was in the old discovery.yml was covering the same thing.

image

**Review by pnadolny13 — APPROVED** [review]
@z3z1ma awesome thanks for clarifying for me!

**Pull request merged**
