### PR TITLE
Add warning for hidden and noindex

### PR DESCRIPTION
**Pull request by tayloramurphy**
Example page where this should appear and noindex should be set

https://deploy-preview-1377--meltano-hub.netlify.app/loaders/target-snowflake--meltano/

Page where robots content is all

https://deploy-preview-1377--meltano-hub.netlify.app/loaders/target-snowflake--meltanolabs/

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@javajunky would you be able to help me out with this? I'm trying to get `rel="noindex"` set in the meta tag but only for pages that have `hidden: true`. I took a stab at it but the rendered HTML doesn't seem to have it. Any ideas what I'm doing wrong here?

**Comment by javajunky** [comment]
@tayloramurphy I think I got the code working the way you want.

**Review by pnadolny13 — APPROVED** [review]
@tayloramurphy looks good to me, you could also optionally add caution emojis like we did for airbyte warnings in the past. I also created https://github.com/meltano/meltano/issues/7796 to make sure these variants arent showing up in the CLI discover command.

**Comment by tayloramurphy** [comment]
Looks good - thank you @javajunky

**Pull request merged**
