### PR TITLE
feat: Show last updated badge for alternate plugin variants

### LINKED ISSUE #1293: feat: Display last commit date in variants list
Specially for plugins with more than a handful of variants, it'd be useful to tell if variants seem abandoned.

For example, `tap-purecloud` has many variants but none seem to have been updated after 2021:

Screenshot 2023-05-04 at 16 31 58

It's hard to tell which is most recently updated variant (and whether that's the default) without clicking through all the variants.

We probably want to strike a balance between

1. having a default variant based on a public set of criteria (https://github.com/meltano/hub/issues/1292)
2. and making it easy for the user to decide which variant to use if they determine the default does not suit their needs

### PR DESCRIPTION
**Pull request by ReubenFrankel**
Closes #1293

image

Happy to add "Last updated" back, but thought it looked cleaner without - or we can do something on hover as suggested in #1293.

### CODE REVIEW

**Comment by ReubenFrankel** [comment]
We could add the Airbyte badge back once https://github.com/badges/shields/pull/10041 is released (i.e. last commit for connector path in the repo).

**Comment by edgarrmondragon** [comment]
I think @tayloramurphy had some concerns about the limited real-estate in the current plugin pages so I kinda wanna let him comment

**Comment by tayloramurphy** [comment]
@edgarrmondragon @pnadolny13 can we get the build for this working so I can see a preview? Hard to compare with just a screenshot.

**Comment by edgarrmondragon** [comment]
Thanks for fixing the build @ReubenFrankel!

Things do seem a bit crowded on mobile:



cc @tayloramurphy 

https://deploy-preview-1719--meltano-hub.netlify.app/extractors/tap-tiktok

**Comment by ReubenFrankel** [comment]
@edgarrmondragon Ah yeah, that doesn't look amazing... I forgot about mobile.

**Comment by tayloramurphy** [comment]
I don't _love_ this. The badging was an attempt to indicate overall quality - but I get why you'd just want to see the latest quick ASAP. 

I like the proposal of a hover or tap to view some of the data - maybe based on the badge? @pnadolny13 what do you think?

**Comment by pnadolny13** [comment]
>I like the proposal of a hover or tap to view some of the data - maybe based on the badge?

I agree that seeing all of the variant metadata next to each other helps a lot when comparing. The idea of a hover sounds nice. If we had a `Compare variants` tool tip that would be super nice. Like put all the variants next to each other in a tabular view to compare across the board. Idk how challenging these types of things are though.

**Comment by ReubenFrankel** [comment]
I'll have a look into a tooltip implementation when I find some more time to work on this. :slightly_smiling_face:

**Comment by ReubenFrankel** [comment]
Current state:

image

> If we had a Compare variants tool tip that would be ideal. Like put all the variants next to each other in a tabular view to compare across the board that pops up when you click.

Wasn't quite sure how to interpret this, but sounds like it would benefit from a design first - I imagine you would want to compare across more than just last updated date, such as quality and built with the SDK (i.e. existing badges)?

**Comment by tayloramurphy** [comment]
I deployed a preview to https://deploy-preview-1779--meltano-hub.netlify.app/extractors/tap-purecloud but the hovers don't seem to work? @pnadolny13 any idea?

**Comment by ReubenFrankel** [comment]
@tayloramurphy I think that deploy was targeting https://github.com/meltano/hub/commit/e78acb7ca5f406e9fe7c1751495d8842c4f40b5a, which I accidentally pushed to this branch the other day (hence previous force-push back).

https://github.com/meltano/hub/actions/runs/9428997282

**Comment by edgarrmondragon** [comment]
the tooltip badges look a lot better 🙌

**Review by tayloramurphy — APPROVED** [review]
I like it 👍

**Comment by pnadolny13** [comment]
@ReubenFrankel this is awesome! Thanks for contributing this.

**Pull request merged**
