### PR TITLE
feat: Auto-select search

### LINKED ISSUE #1619: feat: Default to cursor selection being in the search window
When I go to https://hub.meltano.com it'd be great if I could just start typing the related tap/target/util I"m after instead of having to click. This is super picky and not a big deal :D

### PR DESCRIPTION
**Pull request by ReubenFrankel**
Closes #1619, addresses a related Vue.js warning and fixes some (I assume) intended but non-functional behaviour around search blur.

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
I don't if it's just my browser but I'm seeing a weird behavior where typing into the auto-focused search box doesn't display matches, but clicking outside and then again inside the search box fixes it.

**Comment by ReubenFrankel** [comment]
@edgarrmondragon I don't see that on my end, but I definitely have ran into an issue like that before where I've managed to start typing in the search bar before the page has completely loaded (slow connection or something).

[Screencast from 20-03-24 20:26:51.webm](https://github.com/meltano/hub/assets/60552974/3bb1c44c-a83c-4e93-8055-0c6f0e672ba1)

**Comment by ReubenFrankel** [comment]
@edgarrmondragon This is what I'm talking about. Is this what you're seeing?

[Screencast from 20-03-24 21:04:32.webm](https://github.com/meltano/hub/assets/60552974/4939283e-f326-44b8-bce5-d627e1daaf20)

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I don't see that on my end, but I definitely have ran into an issue like that before where I've managed to start typing in the search bar before the page has completely loaded (slow connection or something).

That's a separate issue which I've also experienced, but this is different:

1. load the page
2. focus is on Search
3. start typing
4. matches list does not come up
5. change focus to another element (e.g. by clicking anywhere outside Search but Tab has the same effect)
6. focus on Search again (click or Shift+Tab)
7. matches list is now displayed

[Kapture 2024-03-20 at 16.20.38.webm](https://github.com/meltano/hub/assets/16805946/e4d6afc9-e688-4029-a90d-6ff80d8afbe2)

**Comment by ReubenFrankel** [comment]
@edgarrmondragon Can you try again now?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon Can you try again now?

Yup, that did it!

**Pull request merged**
