### PR TITLE
target-csv hotglue, remove version pin

### PR DESCRIPTION
**Pull request by visch**
Version pin caused a Windows failure for me. I like to pin, but on my own terms :D

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
> Version pin caused a Windows failure for me

@visch what's the specific failure you saw? Cause it might be a bug in Meltano if git refs can't be used in pip URLs on Windows 😬.

> I like to pin, but on my own terms

You can still override `pip_url` in `meltano.yml` AFAICT. I'm not sure where we're gonna land on pinning versions in the Hub vs resolving/pinning them when a lockfile is generated.

**Comment by visch** [comment]
> > Version pin caused a Windows failure for me
> 
> @visch what's the specific failure you saw? Cause it might be a bug in Meltano if git refs can't be used in pip URLs on Windows 😬.
> 
> > I like to pin, but on my own terms
> 
> You can still override `pip_url` in `meltano.yml` AFAICT. I'm not sure where we're gonna land on pinning versions in the Hub vs resolving/pinning them when a lockfile is generated.

Sorry for the lack of detail, late night!

Specifically it was this issue https://github.com/hotgluexyz/target-csv/issues/1 which their team fixed in a seperate commit, just a tap related issue. We could bump the version here but based on the other taps/targets we're not doing that for others?

**Comment by aaronsteers** [comment]
This is admittedly a hard problem. Discussion started here: https://github.com/meltano/meltano/discussions/6445

**Comment by pnadolny13** [comment]
@aaronsteers @edgarrmondragon @rwfeather how do we feel about merging this?

I'm with Derek that, at least in the short term until we have a pinning strategy, we should unpin and recommend users pin in their own project. The majority of the plugins on the hub right now are already unpinned, I only see 3 that are pinned right now and one of them ended up causing this bug https://github.com/meltano/hub/issues/708.

**Review by pnadolny13 — APPROVED** [review]
@visch this looks good to me! Sounds like we'll go towards not pinning until we have a better strategy for maintaining versions.

**Pull request merged**
