### PR TITLE
feat: Do not display hidden settings

### PR DESCRIPTION
**Pull request by ReubenFrankel**
Follow-on from #1872 and related to #1418

### CODE REVIEW

**Comment by ReubenFrankel** [comment]
I believe `tap-googleads` is currently the only plugin with any hidden settings: https://github.com/meltano/hub/blob/fb5940bebe1cdfb95a0c78e283fa901b622ba9da/_data/meltano/extractors/tap-googleads/matatika.yml#L54

**Comment by edgarrmondragon** [comment]
I'm having second thought on the semantics of `hidden`.

@ReubenFrankel do you feel like it's more intended for UIs that display (and set) Meltano plugin config? For example, for settings that may not be user-friendly.

**Comment by ReubenFrankel** [comment]
> I'm having second thought on the semantics of `hidden`.
> 
> @ReubenFrankel do you feel like it's more intended for UIs that display (and set) Meltano plugin config? For example, for settings that may not be user-friendly.
> 
> So, I wonder if we need a `deprecated` flag to better reflect situations like this.

We use `hidden` for that exact purpose in our UI, where some settings are hidden deliberately as they should be configured by the system only. I understand where you are coming from though, it's just odd that `hidden` isn't (I don't think) used anywhere in the CLI or Hub currently - I guess it was a hang-over from the old Meltano UI?

Totally fine by me to drop this, especially since it's just `tap-googleads` that this would "benefit". Until more plugins are actively deprecating settings, I don't think the flag is super necessary.

**Comment by edgarrmondragon** [comment]
@ReubenFrankel let's just keep the deprecation notice in the setting description. We can look at adding a `deprecated` to Meltano and the Hub plugin schema flag later on.

**Comment by edgarrmondragon** [comment]
> I guess it was a hang-over from the old Meltano UI?

Yeah, but it also doesn't cost us much keeping it around, and is still useful for anyone trying to implementing any sort of settings UI for Meltano 🙂

**Comment by ReubenFrankel** [comment]
> > I guess it was a hang-over from the old Meltano UI?
> 
> Yeah, but it also doesn't cost us much keeping it around, and is still useful for anyone trying to implementing any sort of settings UI for Meltano 🙂 

Fair enough, definitely not proposing removing it, especially since we use it 😅

**Pull request closed without merging**
