### PR TITLE
[feat] Better utility script and set up

### PR DESCRIPTION
**Pull request by z3z1ma**
Added utility to easily spot out all variants with incorrect names. Add pyproject toml so we can run utils more conveniently and manage deps. Updated old jsonschema util to point to correct dirs. 

Fixed lingering tap misname with utility output ;) 

Ran isort and black.

Added name check to CI

### CODE REVIEW

**Comment by aaronsteers** [comment]
@pnadolny13 - Can you review this one? Looks good from my side, but I think you and Taylor are closest to this code.

**Comment by z3z1ma** [comment]
So its important to mention as I did in engineering-chatter,

CI has NOT been running jsonschema validation because of incorrect dir in util script. 
It also has a print statement that blows up the logs because of the large number of taps/targets which do not conform to the schema. 

We should drop the print statement for 1️⃣  and hide it behind a verbosity flag

2️⃣  I would also recommend we use pre-commit here. This way we validate users stuff during development?

**Comment by tayloramurphy** [comment]
@z3z1ma thank you for the PR.

@pnadolny13 I'd appreciate a review from you. WRT @z3z1ma's points about the print statement and the pre-commit hook, I think we can address those in separate issues. 

Thoughts on merging even if the validation is failing in this PR and working with a separate issue to get everything passing the validation? Clearly the Hub is "ok" with unvalidated JSON right now, but I don't know if cluttering this PR with all of the fixes is the way to go.

**Comment by tayloramurphy** [comment]
@pnadolny13 sounds good - I've moved #597 to the next iteration. Will you review, approve, and merge this PR if it looks good to your eyes?

**Review by pnadolny13 — APPROVED** [review]
@z3z1ma looks good to me! I'll go ahead and merge it in, then I'm assigned to https://github.com/meltano/hub/issues/597#event-6821157228 to clean up the failing schema tests as a follow on.

**Pull request merged**
