### PR TITLE
Create draft tap/target maintainer guide

### PR DESCRIPTION
**Pull request by afolson**

### CODE REVIEW

**Comment by afolson** [comment]
@rwfeather @cjohnhanson I can't seem to remove you as reviewers on this draft but feel free to ignore for now.

**Comment by afolson** [comment]
Related issues: 
- https://github.com/meltano/internal-marketing/issues/721
- https://github.com/meltano/internal-marketing/issues/620

**Comment by afolson** [comment]
Still need to answer: ---

```## What happens if a repo gets deleted? I don’t want to risk using a variant if it could be deleted in the future? Should I be keeping a fork in my own namespace? Hard fork?```

This is something that happened on npm and it ended up breaking thousands of builds. Should we mirror the ones we know about? That's a huge undertaking.

**Comment by afolson** [comment]
@DouweM @sbalnojan @tayloramurphy @pnadolny13 @aaronsteers Here's where I'm at with the draft of the add a tap guide as well as the tap maintainer guide. I'd love to get your feedback on it so far and can implement it when I get back from break. Thanks!

There are two TBD sections:

`How can I become a maintainer in MeltanoLabs?` and `How do I stop being a maintainer?`

Do we have a process for adding maintainers to MeltanoLabs? I know we've added folks in the past but I vaguely remember there being some permissions issue with that.

If folks want to step down I think they can just post it on Slack or open an issue somewhere. Does Singer Most Wanted make sense?

**Comment by aaronsteers** [comment]
> There are two TBD sections:
> 
> `How can I become a maintainer in MeltanoLabs?` and `How do I stop being a maintainer?`
> 
> Do we have a process for adding maintainers to MeltanoLabs? I know we've added folks in the past but I vaguely remember there being some permissions issue with that.
> 
> If folks want to step down I think they can just post it on Slack or open an issue somewhere. Does Singer Most Wanted make sense?

Seems like some of this content overlaps with the content in https://github.com/MeltanoLabs/Meta that @pnadolny13 created when we were starting things up. As an aside, we probably should cross-link or merge content between these two sources were applicable or overlapping. This page may also address some of the questions on 'how are folks added'. Admittedly, we may still want to update/change those processes, but there is some process documentation there we can use, recycle, or change.

**Comment by aaronsteers** [comment]
> Still need to answer:
> 
> `## What happens if a repo gets deleted? I don’t want to risk using a variant if it could be deleted in the future? Should I be keeping a fork in my own namespace? Hard fork?`
> 
> This is something that happened on npm and it ended up breaking thousands of builds. Should we mirror the ones we know about? That's a huge undertaking.

We don't have a mitigation as of now but if it is a broad concern, we should absolutely create a new issue to propose solutions. Meltano Cloud will likely cache at least the virtualenv directories at some time in the future, and we could also consider serving from our own PyPi-like server, but caching or archiving the repo itself is another matter.

Any way we want to solve this though, the scope is very large.

**Comment by afolson** [comment]
@aaronsteers Thanks for the meta link! I totally forgot about that repo. Good stuff.

The mirroring question came up in one of the issues related to this PR. For now I think it's enough to just mention that folks may want to create their own mirrors if they depend on a plugin in production, personally.

**Comment by afolson** [comment]
@pnadolny13 @tayloramurphy @sbalnojan Would you mind reviewing? Thanks!

**Review by aaronsteers — DISMISSED** [review]
I don't see any incoming links from other pages on hub.meltano.com. Can we add one or more means to navigate to these new pages?

Thanks!

**Comment by afolson** [comment]
@aaronsteers I added a new dropdown for docs as that seemed like the best place to put these sorts of things. Will that work?

@DouweM Just FYI in case the website team has already made wireframes for this. I think going forward we should make the docs more obvious on the hub.

**Comment by afolson** [comment]
@tayloramurphy Does the dropdown work for you? I think having a docs section is probably good here.

**Review by tayloramurphy — APPROVED** [review]
Pat is going to create a new PR with the updates he has. Approving so we can merge!

**Review by pnadolny13 — APPROVED** [review]
@afolson LGTM! I'll add my additional FAQ questions/content in a follow on PR.

**Comment by pnadolny13** [comment]
@afolson I've seen this weird error youre getting before https://github.com/meltano/hub/actions/runs/3998314494/jobs/6860791848, if you update your branch this usually goes away.

**Pull request merged**
