### PR TITLE
Add more missing settings

### PR DESCRIPTION
**Pull request by pnadolny13**
As I was working on investigating https://github.com/meltano/internal-data/issues/38 and https://github.com/meltano/internal-data/issues/39 I was taking note of some connectors that didnt have settings and where users got tripped up and didnt make it through the funnel. I updated some of them here so they have settings.

### CODE REVIEW

**Review by aaronsteers — APPROVED** [review]
@pnadolny13  I did a scan through and nothing popped out to me. I do appreciate the mindfulness in updating maintenance status where it seems appropriate to do so.

Let me know if you need a deeper review on any particular part. Otherwise, I think this is probably ready to go.

**Comment by aaronsteers** [comment]
Sidebar: Not important enough to slow down this PR for, but I did find myself wishing we had a sort order applied to yaml keys here.

Taking this one as an this example:

```yml
description: Customer Relationship Management Platform
label: Close
name: tap-closeio
logo_url: /assets/logos/extractors/closeio.png
namespace: tap_closeio
variant: singer-io
pip_url: tap-closeio
repo: https://github.com/singer-io/tap-closeio
settings:
#...
capabilities:
#...
domain_url: https://close.com/
maintenance_status: active
keywords:
#...
settings_group_validation:
#...
```

I'd find an ordering like this much easier to scan:

```yml
name: tap-closeio
variant: singer-io
maintenance_status: active
label: Close
description: Customer Relationship Management Platform
namespace: tap_closeio

pip_url: tap-closeio
domain_url: https://close.com/
logo_url: /assets/logos/extractors/closeio.png
repo: https://github.com/singer-io/tap-closeio

keywords:
#...
capabilities:
#...
settings_group_validation:
#...
settings:
#...
```

**Comment by pnadolny13** [comment]
@aaronsteers Thanks for reviewing again!!

>Sidebar: Not important enough to slow down this PR for, but I did find myself wishing we had a sort order applied to yaml keys here.

I completely agree, the script I'm using was writing them in sorted order but then the diff was big and confusing. I'd vote for a 1 time PR that sorts everything. In addition to that we can also add a CI test that makes sure sort order is enforced.

**Comment by tayloramurphy** [comment]
@pnadolny13 great work on this PR. These are the ones that are kind of annoying to do but have huge impact for the community.

And agreed on having a logical (non-alphabetical) sort order.

**Pull request merged**
