### PR TITLE
Add tap-quickbase-json

### PR DESCRIPTION
**Pull request by gnilrets**
All Singer definitions are stored in `/_data/taps/` or `/_data/targets`. The minimal requirement for adding a tap or target will match the following format:

```yaml
description: General description of what the company behind the API does
entity_type: Review the JSON Schema for latest options. Currently api, file, database.
entity_url: URL of the developer documentation or website
label: Properly formatted label of the connector
name: The unique name of the connector
singer_name: The Singer specific name of the connector. Typically tap-<name> or target-<name>
type: tap or target
variants: # an array of variant types
- default: true or false
  maintenance_status: "Options: active, beta, development, inactive, unknown"
  meltano_sdk: true or false
  name: Name of the GitHub/GitLab namespace
  pip_url: git+<git_url>.git or pip instal name
  repo: repo URL
  capabilities:
    - catalog
    - discover
  settings:
    # Can be an empty array if unknown: []
    # Describe the list of supported settings, for example:
    - name: project_ids
      kind: array
      label: Project IDs
      description: Array of project IDs.
    - name: username
      label: Username
      description: Credentials used when for connecting to the source.
    - name: password
      kind: password
      label: Password
      description: Credentials used when for connecting to the source.
```

## Checklist

- [ ] Add/update the file in the appropriate folder (`/taps` or `/targets`). The name of the file should match the name of the tap. If there is already one, add a descriptor to the name such as `-search`.
- [ ] Add/update the PNG logo image in `/assets/logos/<taps or targets>`. The image name must match the YAML file name.
- [ ] Tag `@tayloramurphy` or `@pnadolny13` to flag it for review. Or post to the [#hub](https://meltano.slack.com/archives/C01UGBSJNG5) channel on Meltano slack.

## Reviewer Checklist

- [ ] Validate file against JSON Schema. https://www.jsonschema.net/home is an option.
- [ ] Build website locally and validate everything works.

### CODE REVIEW

**Comment by pnadolny13** [comment]
@gnilrets thanks for opening this!

I saw your message in slack about it being unclear how to submit a plugin, I opened https://github.com/meltano/hub/issues/711 and https://github.com/meltano/hub/issues/710 related to that, feel free to add comments based on your experience so we can make it easier for the next person.

We changed the structured of the plugin definitions as part of the meltano 2.0 release and it looks like your changes (and the issue template) still follow the old structure. I'd recommend checking out something like https://github.com/meltano/hub/blob/main/_data/meltano/extractors/tap-tiktok/gthesheep.yml for an example structure and the [docs](https://docs.meltano.com/reference/plugin-definition-syntax#undefined) for detail on what the fields mean. Each variant of that plugin lives in its own file under a directory named after the plugin i.e. `tap-quickbase-json/mainspringenergy.yml`.

Also I see [tap-quickbase](https://github.com/meltano/hub/tree/main/_data/meltano/extractors/tap-quickbase) already exists although they look to use different APIs, can you confirm that these should be listed as 2 separate taps on the hub vs variants under the same name? Is your tap's json endpoint the new API and the existing tap-quickbase variants use a legacy API, or are they 2 distinct things?

**Comment by gnilrets** [comment]
Ok, I just followed the instructions in the template.  What exactly needs to be addressed?

Yeah, tap-quickbase uses a legacy XML-based API that is so underperforming it would have taken 1 year to extract all of our Quickbase data.  It felt like a new thing to me, but it taps the same SaaS tool so I'm not fully clear on whether it's a variant or a new tap.

**Comment by pnadolny13** [comment]
>Yeah, tap-quickbase uses a legacy XML-based API that is so underperforming it would have taken 1 year to extract all of our Quickbase data. It felt like a new thing to me, but it taps the same SaaS tool so I'm not fully clear on whether it's a variant or a new tap.

@gnilrets do you know if it has the same coverage as the existing taps? If its the same then I'd prefer to make yours the default under the same tap-quickspace name on the hub.

>Ok, I just followed the instructions in the template. What exactly needs to be addressed?

@gnilrets yeah sorry about that, I updated in the issue template so its updated moving forward. 

The things to update shouldnt be to bad, you just need to restructure your yaml to match the structure from the updated issue template or use the reference I linked in my comment above 😄 :

>I'd recommend checking out something like https://github.com/meltano/hub/blob/main/_data/meltano/extractors/tap-tiktok/gthesheep.yml for an example structure and the [docs](https://docs.meltano.com/reference/plugin-definition-syntax) for detail on what the fields mean. Each variant of that plugin lives in its own file under a directory named after the plugin i.e. tap-quickbase-json/mainspringenergy.yml.

Also it looks like this is the first variant under the `mainspringenergy` name so you'll want to add your name to the [maintainers file](https://github.com/meltano/hub/blob/main/_data/maintainers.yml).

So our todos are:

- [ ]  add name to maintainers file
- [ ]  restructure your yml file
- [ ]  we need to decide if we should put this tap under the existing tap-quickbase namespace on the hub or under a new tap-quickbase-json. Depending on coverage and if this json tap is the best default moving forward.

**Comment by tayloramurphy** [comment]
>  It felt like a new thing to me, but it taps the same SaaS tool so I'm not fully clear on whether it's a variant or a new tap.

@gnilrets @pnadolny13 if it's pulling from the same source I'd rather we keep it under one entity and just make it the default. Assuming it's pulling mostly the same information.

**Comment by pnadolny13** [comment]
I'm closing this in exchange for https://github.com/meltano/hub/pull/756 that has the updated schema and makes it a variant of tap-quickbase vs a standalone extractor.

**Pull request closed without merging**
