### PR TITLE
feat: add last commit date, streamline sidebar links

### PR DESCRIPTION
**Pull request by aaronsteers**
Addresses

- #896 

<table>
<tr>
	<td>Before <BR/> https://hub.meltano.com/extractors/tap-dynamodb--jannikweichert/
	<td>After <BR/> https://deploy-preview-1138--meltano-hub.netlify.app/extractors/tap-dynamodb--jannikweichert/
<tr>
	<td>image
	<td>image
</table>

- Adds badge for last commit date.
- Removes bare URL for vendor "Homepage". (This is already linked in the first paragraph of the main panel.)
- Removes bare URL for plugin's repo. Replace with badge that shows `user & repo` in cleaner format, with link to the repo.
- Uses custom SVG for GitHub or GitLab icon (Sample with Gitlab hosted repo is here: https://deploy-preview-1138--meltano-hub.netlify.app/extractors/tap-adwords--meltano/)

### CODE REVIEW

**Review by tayloramurphy — APPROVED** [review]
I like it! Nice change

**Comment by tayloramurphy** [comment]
@aaronsteers have you looked at this when there is an EDK link as well? Would be good to get that upated in this PR as well cc @pnadolny13

**Comment by pnadolny13** [comment]
>@aaronsteers have you looked at this when there is an EDK link as well? Would be good to get that upated in this PR as well 

@tayloramurphy the edk repos change isnt in main yet. Its part of https://github.com/meltano/hub/pull/1135.

**Comment by aaronsteers** [comment]
I'll go ahead and merge so this doesn't stack up conflicts.

**Comment by aaronsteers** [comment]
Thanks, @pnadolny13 for explaining context in the above. I was not sure how to reply because this wasn't touching anything related to EDK.

**Pull request merged**
