### PR TITLE
Add Shaped AI tap-iceberg

### PR DESCRIPTION
**Pull request by BTheunissen**
Adds an extractor for Apache Iceberg data. Currently this is a WIP implementation, currently passing all integration tests for local test data, with the aim to support a variety of Iceberg catalog types such as AWS Glue, and supporting features such as incremental replication and delete row propagation.

### CODE REVIEW

**Review by tullie — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
Nice!

**Comment by edgarrmondragon** [comment]
The build is currently failing because of the missing logo file:

```
Error: Cannot find module './extractors/iceberg.png'
```

https://app.netlify.com/sites/meltano-hub/deploys/669940f9ae3ba20008e3509a

**Review by edgarrmondragon — APPROVED** [review]
Thanks @BTheunissen!

**Comment by BTheunissen** [comment]
No worries @edgarrmondragon thanks for the quick merge. Now to import this into our project to test, and add some more functionality to the tap!

**Pull request merged**
