### PR TITLE
Move GE docs from Meltano Docs

### PR DESCRIPTION
**Pull request by tayloramurphy**
Related to #253 and https://github.com/meltano/meltano/pull/5990

Moves the GE docs to the Hub

### CODE REVIEW

**Comment by aaronsteers** [comment]
Just to confirm regarding file name, Is the variant name 'great-expecations' or 'meltano' / 'meltanolabs'?

**Review by aaronsteers — COMMENTED** [review]
@tayloramurphy - Just to confirm regarding file name, Is the variant name 'great-expecations' or 'meltano' / 'meltanolabs'?

**Comment by tayloramurphy** [comment]
@aaronsteers full file is::

```yaml
name: great_expectations
namespace: great_expectations
pip_url: great_expectations
executable: great_expectations
variant: great-expectations
settings:
- name: ge_home
  value: $MELTANO_PROJECT_ROOT/utilities/great_expectations
  env: GE_HOME
logo_url: /assets/logos/utilities/great_expectations.png
```

so it's great_expectations/great-expectations

**Comment by aaronsteers** [comment]
@tayloramurphy - Thanks for confirming. 👍

**Review by aaronsteers — APPROVED** [review]

**Pull request merged**
