### PR TITLE
Add commands to plugin pages

### PR DESCRIPTION
**Pull request by tayloramurphy**
Closes https://github.com/meltano/hub/issues/894

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@cjohnhanson @rwfeather can one of y'all tell me what I'm doing wrong on this PR? It looks like the commands section is already built we're just not pulling it into the plugin pages. Pretty sure I don't know what I"m doing with the graphql query!

**Comment by rwfeather** [comment]
> @cjohnhanson @rwfeather can one of y'all tell me what I'm doing wrong on this PR? It looks like the commands section is already built we're just not pulling it into the plugin pages. Pretty sure I don't know what I"m doing with the graphql query!

This seems to come from how the `commands` section in the yaml is formatted. You'll notice that the `settings` is an array, where the `commands` uses the command name as keys:

Screen Shot 2022-11-15 at 11 14 34 AM

The gridsome importer is going to handle those two things fairly differently, affecting how they can be queried in graphql.

@tayloramurphy If you don't mind, there's probably a quick fix that I can contribute to your branch 😄

**Comment by tayloramurphy** [comment]
@rwfeather I saw the difference in data structure and tried to copy the edges/nodes query below the plugin one but with no luck 😅 you're very welcome to push commits to this branch!

**Comment by tayloramurphy** [comment]
@rwfeather I see the commands on the page now but it seems like it messes up the sidebar quite a bit https://deploy-preview-1007--meltano-hub.netlify.app/utilities/airflow

I'd say don't worry about this right now unless you think it's a quick fix. I'll sync with @aaronsteers on prioritization 😄

**Comment by aaronsteers** [comment]
@cjohnhanson - As I noted on the issue #894, as you have time open up, feel free to pick this up. Thanks for your help!

**Comment by cjohnhanson** [comment]
> @rwfeather I see the commands on the page now but it seems like it messes up the sidebar quite a bit https://deploy-preview-1007--meltano-hub.netlify.app/utilities/airflow
> 
> I'd say don't worry about this right now unless you think it's a quick fix. I'll sync with @aaronsteers on prioritization 😄

@tayloramurphy the sidebar looks alright to me with these changes. The only difference is that it's a bit narrower. Do we want the sidebar to be fixed width? What's the messed up behavior that you're seeing?

**Comment by cjohnhanson** [comment]
@tayloramurphy yeah weird, I was able to replicate on Firefox.

I took a stab at resolving the two overflow issues here:
- For the commands section, the inline "Equivalent to:" code blocks will now wrap text 
- Within the "Next Steps" section, rendered code blocks will now be styled the same as other code blocks and have horizontal scrolling for any overflow.

How does this look to you? Aside from the overflow issues, I think styling the code blocks within "Next steps" to be consistent with all the rest of our code blocks is probably a good move in and of itself. I'll go ahead and mark this as "Ready for review", let me know if you think there are some additional changes we should make here.

**Comment by tayloramurphy** [comment]
@cjohnhanson this fixed that particular overflow and sidebar issue and I like how the commands look. I think we'll have to tackle separately the weirdly sized sidebar, but that's been a bug for a while. I'm going to approve from a Product side! Thanks so much! 

FYI @sbalnojan we should announce this on slack once it's merged b/c some folks have been asking for it!

Looks like I can't approve b/c i opened the PR originally, but consider this Product approval ✅ 😅

**Review by cjohnhanson — APPROVED** [review]

**Pull request merged**
