### PR TITLE
take edk utilities out of preview

### PR DESCRIPTION
**Pull request by pnadolny13**
Closes https://github.com/meltano/hub/issues/1115

- hides transformers, ochestrators, and associated files from search.
- removes the transformer and orchestrator options from the plugin drop down menu
- those pages still exist if you have a url and are still served via the API
- adds the edk repo url to the side bar in the plugin page below repo
- ~I drafted some changes to the Airflow plugin page to remove "preview" and the description. I figured once we get airflow in a good place I can update the other 6-7 utilities with the same language.~
  - ~do we still want a section to mention that its EDK based and what the EDK is? or does it not matter anymore?~
  - ~we need some consistency with our edk naming convention, some are named after meltano and some are named after the source package owner i.e. airflow is the apache variant, most dbt plugins are the dbt-labs variant, but dbt-duckdb is jwillis, and superset has both apache and meltano. I think if we use an edk then it should be the variant.~

Update: I added a section to every edk based plugin that explains what it is. I also adjusted how I hide those plugins from search so they still exists on plugin landings pages (i.e. transformers) but dont show up in search, this includes the associated files bundles.

@tayloramurphy what do you think?

Deploy preview:

- https://deploy-preview-1135--meltano-hub.netlify.app/

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@pnadolny13 excited to see this. We need to pair this with a corresponding PR to the docs themselves as there are several resources that recommend the non-utility versions of these plugins. I chatted this morning with @sbalnojan and @aaronsteers about this and we're generally supportive of it, but there are some considerations for existing users that we may want to account for.

**Comment by pnadolny13** [comment]
@tayloramurphy sounds good! Since the legacy pages still exist and are still served with the API I figured this wasnt blocked by the docs updates. We're only excluding these plugins from being discoverable on the hub.

**Comment by pnadolny13** [comment]
> we need some consistency with our edk naming convention, some are named after meltano and some are named after the source package owner i.e. airflow is the apache variant, most dbt plugins are the dbt-labs variant, but dbt-duckdb is jwillis, and superset has both apache and meltano. I think if we use an edk then it should be the variant.

@tayloramurphy related to variant names and ^^ I still think Superset is still a weird case. We have apache for the direct pip install and meltano for the extension version, both would be apache if we went by the source code naming. I also think theres a chance that we will get multiple EDK variants that have different features, what do you think about doing `<source code org name>-<edk extension org name>` (or a similar combo of the 2 names) as the variant so we'd have:
- `apache` and `apache-meltano` for superset
- dbt-snowflake -> `dbt-labs-meltano`
- dbt-duckdb -> `jwills-meltano`

**Comment by pnadolny13** [comment]
@tayloramurphy I made the updates that we talked about. Let me know what you think.

**Comment by tayloramurphy** [comment]
@pnadolny13 what do you think about hiding the related files (dbt, airflow)? That would bring it back down to just datahub, docker, docker compose, gitlab ci, and great expectations.

**Comment by pnadolny13** [comment]
@tayloramurphy hiding from search and the files plugin page? Right now it should already be hidden in search but I can switch to remove them from the plugin page too. I think that makes sense and might be less confusing for users to not see those at all.

**Comment by tayloramurphy** [comment]
@pnadolny13 I just pushed up a change to hide the dbt files.

**Comment by tayloramurphy** [comment]
Docs PR is merged. We can merge this on 2/3 it looks like.

**Pull request merged**
